"""Regression tests for the repository verification contract."""
from __future__ import annotations

import shutil
import subprocess
import sys
import tempfile
import unittest
from datetime import date
from pathlib import Path


SOURCE_ROOT = Path(__file__).resolve().parents[1]


class CheckScriptTests(unittest.TestCase):
    def setUp(self):
        self.temporary_directory = tempfile.TemporaryDirectory()
        self.root = Path(self.temporary_directory.name) / "template"
        shutil.copytree(
            SOURCE_ROOT,
            self.root,
            ignore=shutil.ignore_patterns(".git", "__pycache__", "*.pyc", "research-project-template.zip"),
        )

    def tearDown(self):
        self.temporary_directory.cleanup()

    def check(self, *arguments):
        return subprocess.run(
            [sys.executable, "scripts/check.py", *arguments],
            cwd=self.root,
            text=True,
            capture_output=True,
            check=False,
        )

    def write(self, relative_path, content):
        (self.root / relative_path).write_text(content, encoding="utf-8")

    def test_static_baseline_passes(self):
        result = self.check("--static")
        self.assertEqual(result.returncode, 0, result.stderr)

    def test_disabled_paper_accepts_not_applicable_location(self):
        profile = (self.root / "PROJECT_PROFILE.toml").read_text(encoding="utf-8")
        ledger = (self.root / "docs/CLAIM_LEDGER.md").read_text(encoding="utf-8")
        self.write("PROJECT_PROFILE.toml", profile.replace("paper = true", "paper = false"))
        self.write(
            "docs/CLAIM_LEDGER.md",
            ledger.replace("paper/sections/03_formalisation.tex", "—").replace("paper/sections/02_method.tex", "—"),
        )
        result = self.check("--static")
        self.assertEqual(result.returncode, 0, result.stderr)

    def test_formal_claim_fails_without_formal_module(self):
        profile = (self.root / "PROJECT_PROFILE.toml").read_text(encoding="utf-8")
        self.write("PROJECT_PROFILE.toml", profile.replace("formal = true", "formal = false"))
        result = self.check("--static")
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("formal theorem claim requires active formal module", result.stderr)

    def test_paper_version_mismatch_fails(self):
        version_source = (self.root / "paper/PAPER_VERSION.tex").read_text(encoding="utf-8")
        self.write("paper/PAPER_VERSION.tex", version_source.replace("0.1.0", "0.1.1"))
        result = self.check("--static")
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("paper version differs", result.stderr)

    def test_bounded_claim_requires_structured_bounded_scope(self):
        ledger = (self.root / "docs/CLAIM_LEDGER.md").read_text(encoding="utf-8")
        ledger = ledger.replace("| C-001 | formal-theorem |", "| C-001 | bounded-exhaustive-check |")
        self.write("docs/CLAIM_LEDGER.md", ledger)
        result = self.check("--static")
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("bounded evidence needs a bounded: scope", result.stderr)

    def test_analysis_contract_creates_declared_output(self):
        profile = (self.root / "PROJECT_PROFILE.toml").read_text(encoding="utf-8")
        ledger = (self.root / "docs/CLAIM_LEDGER.md").read_text(encoding="utf-8")
        self.write("PROJECT_PROFILE.toml", profile.replace("formal = true", "formal = false"))
        self.write(
            "docs/CLAIM_LEDGER.md",
            ledger.replace("| C-001 | formal-theorem |", "| C-001 | computational-experiment |").replace(
                "formal/lean/TemplateFormalization/Basic.lean#modus_ponens", "analysis/generate_figure.py"
            ),
        )
        output = self.root / "paper/figures/generated/example-data.tex"
        output.unlink(missing_ok=True)
        result = self.check()
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertTrue(output.is_file())
        self.assertIn("Generated by analysis/generate_figure.py", output.read_text(encoding="utf-8"))

    @unittest.skipUnless(shutil.which("latexmk"), "latexmk is not installed")
    def test_paper_command_builds_after_analysis(self):
        profile = (self.root / "PROJECT_PROFILE.toml").read_text(encoding="utf-8")
        ledger = (self.root / "docs/CLAIM_LEDGER.md").read_text(encoding="utf-8")
        self.write("PROJECT_PROFILE.toml", profile.replace("formal = true", "formal = false"))
        self.write(
            "docs/CLAIM_LEDGER.md",
            ledger.replace("| C-001 | formal-theorem |", "| C-001 | computational-experiment |").replace(
                "formal/lean/TemplateFormalization/Basic.lean#modus_ponens", "analysis/generate_figure.py"
            ),
        )
        result = self.check("--paper")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertTrue((self.root / "paper/main.pdf").is_file())
        self.assertTrue((self.root / "paper/renders" / f"project-name-v0.1.0-{date.today().isoformat()}.pdf").is_file())

    def test_release_flag_rejects_disabled_release(self):
        result = self.check("--static", "--release")
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("release checks disabled", result.stderr)

    def test_release_accepts_complete_citation_metadata(self):
        profile = (self.root / "PROJECT_PROFILE.toml").read_text(encoding="utf-8")
        self.write("PROJECT_PROFILE.toml", profile.replace("enabled = false", "enabled = true"))
        self.write(
            "CITATION.cff",
            """cff-version: 1.2.0
title: \"Verification Example\"
authors:
  - family-names: \"Example\"
    given-names: \"Ada\"
version: 0.1.0
date-released: 2026-08-24
""",
        )
        result = self.check("--static", "--release")
        self.assertEqual(result.returncode, 0, result.stderr)

    def test_release_rejects_citation_version_mismatch(self):
        profile = (self.root / "PROJECT_PROFILE.toml").read_text(encoding="utf-8")
        self.write("PROJECT_PROFILE.toml", profile.replace("enabled = false", "enabled = true"))
        self.write(
            "CITATION.cff",
            """cff-version: 1.2.0
title: \"Verification Example\"
authors:
  - family-names: \"Example\"
version: 9.9.9
date-released: 2026-08-24
""",
        )
        result = self.check("--static", "--release")
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("CITATION.cff version must match paper.version", result.stderr)


if __name__ == "__main__":
    unittest.main()
