"""Example deterministic figure input generator.

Replace this with project-specific analysis. It intentionally uses only the Python
standard library so the template has no hidden environment dependency.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "paper" / "figures" / "generated" / "example-data.tex"

OUTPUT.parent.mkdir(parents=True, exist_ok=True)
OUTPUT.write_text(
    "% Generated by analysis/generate_figure.py. Do not edit manually.\n"
    "\\begin{figure}[h]\n"
    "  \\centering\n"
    "  \\fbox{\\parbox{0.72\\linewidth}{\\centering Deterministic analysis placeholder}}\n"
    "  \\caption{Example output generated from tracked analysis source.}\n"
    "  \\label{fig:generated-example}\n"
    "\\end{figure}\n",
    encoding="utf-8",
)
print(f"wrote {OUTPUT.relative_to(ROOT)}")
